### ISSUE TITLE
The Data in Catalogue

### ISSUE THREAD

**Issue by Xiyuqiao** [HeRTA/FRBSTATS#32]
Thank you for your efforts in providing visual FRB data.
I found that some data in the Catalogue needs to be checked again.
The flux of FRB 20190614D should be 0.124 Jy. @0xCoto

**Comment by 0xCoto** [comment]
@Xiyuqiao - Good catch, looks like the reporter unintentionally reported the flux to the Transient Name Server under an incorrect unit (mJy instead of Jy). Thanks for reporting this, please let me know if you spot other instances like this!

(The fix has been applied and can be viewed from the FRBSTATS platform)
